services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '80:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@example.com
      - PGADMIN_DEFAULT_PASSWORD=test